export const REFERENCE_PROMPTS = {
    FLASH: [
        // Vibe: Night out, Party, Hard Direct Flash, Chaos
        "medium shot of a woman with a natural skin texture. Her jet black hair is worn down and slightly windblown. She is standing outside a dark apartment door at night, leaning slightly against the doorframe while looking down into a tote bag slung over her shoulder, searching for keys. Her expression is concentrated with a slightly frustrated furrowed brow. She is dressed in a black fitted ribbed tank top, loose-fitting cargo pants, and sneakers. The background features a textured apartment door, a brick wall, and a dark concrete floor under very dim ambient light, suggesting a late-night arrival. The lighting comes from a single direct digital flash, creating hard, sharp shadows against the door and wall behind her. The image captures an authentic unpolished snapshot feel with digital grain visible in the dark areas, sharp focus on the subject, and neutral, slightly washed-out colors typical of direct flash photography. Keep her facial identity consistent from reference photos provided.",
        "Medium-close-up, slightly claustrophobic shot of a woman with natural skin tone and natural texture. Her jet black hair is styled in a messy bun with strands falling loose. She is sitting slumped in the passenger seat of a parked car at night, looking sleepily at the camera with her head tilted against the headrest and a slight smirk. Her makeup is minimal, showing a natural evening skin glow and lip balm, with a slight shine on her forehead from the harsh light coming from somewhere. She wears a grey oversized crewneck sweatshirt and black leggings, with a seatbelt fastened diagonally across her chest and arms crossed loosely. The environment features a dark car ceiling and a blurred view of a dark street outside the window with dashboard lights off. The scene is lit by a harsh, direct, on-camera small LED flash concentrated on her face and chest, causing rapid light fall-off to pitch black in the background. The image has a raw digital snapshot look with high ISO noise in shadows, sharp highlights on skin, realistic digital color processing, and cool digital tones with high contrast.", "Vertical flash photography, half body shot standing near the edge of a rooftop railing. Looking out at the city view, profile visible. The flash hits from the side, illuminating hair strands individually and creating a sharp shadow on the neck. Skin looks incredibly realistic and unretouched. Background is a bokeh field of city lights.",
        "A candid, low-angle full body shot of a woman walking down the steps of a Mediterranean villa during late afternoon. The wind is pressing her lightweight white linen sundress against her body, revealing her silhouette clearly. She has a perfect body shpae as in her photos. She is looking down at her sandals, smiling softly, unaware of the camera. Natural, diffused sunlight bounces off the white walls, creating soft, flattering shadows that highlight the texture of her skin—you can see the natural creases in her neck and the texture of her knees. No plastic doll look; realistic skin tone variation. Shot on Phase One IQ4 150MP, Schneider Kreuznach 80mm LS f/2.8 Blue Ring. Incredible dynamic range, retaining detail in the bright white dress and the shadows of her hair. Keep her face identity exactly consistent from reference photos provided", "Vertical, raw snapshot taken from the driver's seat looking at the passenger in a parked car at night. The harsh, yellowish overhead dome light inside the car is turned on, casting strong downward shadows on the face, highlighting bone structure. Smiling broadly, looking down at a phone with natural skin details.",
        "Medium close-up shot taken from across the table of a female with a natural skin texture. Her jet black hair is styled in a loose ponytail with wispy bangs falling in her eyes. She is sitting in a retro American diner booth, leaning forward over the table with her elbows on the surface and shoulders relaxed. She rests her chin in her palm, looking at the camera with a sleepy but affectionate smile and slightly heavy eyes. She is wearing a tight-fitting black mock-neck long-sleeve top, blue jeans, silver hoop earrings, and a visible nose stud. Her makeup appears as faded evening makeup with glossy lips and a natural slight shine on her skin. The background features red vinyl seating, a condiment holder on the table, and a reflective window behind her showing darkness and street lights, indicating a late night or early morning context. The scene is lit by a direct on-camera flash, creating a strong highlight on her face and a sharp reflection on the window glass. The image evokes a Fujifilm Instax or point-and-shoot aesthetic with high contrast, vintage warm tones, and deep blacks in the shadows.",
        "Candid full body shot of a woman sitting on the concrete curb outside a bright 24-hour convenience store. She is holding a bottle of water, looking up at the camera with a tired but content smirk. The lighting is a mix of the bright white fluorescent store light spilling from behind her (creating a halo effect) and a front-facing camera flash. This lighting combo highlights the texture of the concrete wall and the natural oil on her forehead. She is wearing a denim jacket. Background shows the glass store front with posters. Photo feels like a snapshot taken by a friend. Keep her face identity consistent from reference photos provided.",
    ],
    GOLDEN: [
        // Vibe: Sun, Warmth, Morning/Sunset, 35mm Film
        "A raw, candid, full-body photograph of a woman walking along a wooden beach boardwalk on a breezy, overcast afternoon. The diffused, soft white sky acts as a giant softbox, providing even, flattering, yet highly detailed illumination. The wind is blowing her hair across her face, and she is laughing, trying to brush it away. The soft light reveals the natural tonality and texture of the skin on her legs and midriff—visible pores, tiny hairs (vellus), and natural skin creases around her knees as she walks. She is wearing a flowy, patterned mini skirt that is blowing slightly in the wind, and a tied linen shirt that acts as a crop top. The outfit clearly defines her perfect figure.  Shot on Fujifilm GFX 100S Medium Format, GF 80mm f/1.7 lens, aperture f/2.0. Incredible resolution rendering the wood grain of the boardwalk and the weave of the linen fabric. Soft, muted color palette. Keep her face identity exactly consistent from reference photos provided. style raw.",
        "Vertical, candid shot sitting at an outdoor cafe patio. It is late afternoon. Leaning forward, elbows on the table, listening intently with a soft smile. Dappled sunlight filters through the trees, creating shifting patterns of light and shadow on the face. Skin texture is natural and highly detailed. Shot on Hasselblad H6D-100c, 100mm f/2.2. ",
        "A raw, hyper-realistic photo resting on a park lawn after a bike ride. It is golden hour. Lying on stomach, propped up on elbows, looking up at the camera with a relaxed expression. The low, warm sun highlights individual strands of messy hair and casts a golden glow on skin, preserving authentic facial details. Shot on Leica SL2, 50mm Summilux. ",
        "Vertical shot standing on a beach boardwalk during sunset. The sun is directly behind the subject, creating a beautiful rim light halo around the hair. The face is softly illuminated by the ambient warm glow. Wind is blowing hair slightly. Skin looks warm, natural, and sun-kissed.",
        "Candid car selfie taken from the passenger seat while driving on a highway. The window is down, and the golden hour sun is blasting in, illuminating the face with a warm, orange hue. Sunglasses on head, laughing at the wind. High resolution texture showing true-to-life skin details."
    ],
    GRITTY: [
        // Vibe: Street, Urban, Raw, High ISO, Cold
        "A gritty, candid flash shot sitting side-by-side on a concrete curb late at night, finishing street food. Wiping the corner of mouth with the back of hand, laughing. The direct flash highlights the humidity on skin, making it look dewy and realistic. Background is dark asphalt and blurry lights.",
        "Vertical snapshot taken under a glass bus stop shelter at night. It is cold outside. Head resting on shoulder, eyes half-closed, looking sleepy and content. The direct camera flash reflects slightly off the glass behind and highlights naturally flushed cheeks from the cold air. Skin texture is raw and unretouched.",
        "Vertical, candid shot standing on a crowded city subway train. Looking out the window with a pensive expression, head resting lightly against the glass. Daylight streams in, illuminating dust motes in the air and the texture of skin, showing natural flush and authentic details.",
        "Black and white street photography style. Walking out of a metro station in the rain, holding a newspaper over head. The image is high contrast with grain. The focus is sharp on the eyes, showing raw emotion and natural facial structure without smoothing.",
        "Late night snapshot leaning against a brick wall in an alleyway, holding a lit cigarette (or phone). The lighting is dim and moody, coming from a distant street lamp. The image has high ISO noise/grain. The face is partially in shadow, emphasizing realistic bone structure and skin texture.",
        "Create a raw, documentary-style shot of a me standing by a railing along a city waterfront promenade. It is late afternoon, and the sun is warm. He is looking out over the water, hands in his jacket pockets. A light breeze is blowing his hair slightly. His expression is pensive and calm, with a subtle, almost imperceptible smile. The low sun angle catches the texture of his skin and stubble clearly. The background is the sparkling water and a distant city skyline. Shot on Canon EOS R5, 50mm lens, showing natural grain. Keep his face identity consistent from reference photos provided."
    ],
    CINE: [
        // Vibe: Atmospheric, Neon, No Flash, Moody, Bokeh
        "Vertical candid shot standing on a windy rooftop overlook at night. Leaning against the railing, hair blowing wildly across face, smiling broadly. Illuminated solely by the ambient city glow and a nearby red neon sign, casting a moody hue on the face. Skin texture is detailed and natural against a bokeh skyline.",
        "Cinematic close-up inside a dimly lit jazz bar. Leaning against the velvet booth, holding a glass. The lighting is soft and warm, coming from a table lamp, creating a 'Rembrandt' triangle of light on the cheek. Deep shadows, rich colors. Skin looks authentic and high fidelity.",
        "Vertical shot walking down a rainy street in Tokyo at night. Holding a clear umbrella. The face is illuminated by the glow of blue and pink shop signs reflecting off the wet pavement. No flash. The look is moody and atmospheric with soft focus background.",
        "A quiet moment inside a late-night laundromat. Sitting on top of a washing machine, reading a book. The lighting is cool, clinical white from the fluorescent tubes, but soft and diffused. The composition is symmetrical (Wes Anderson style). Skin texture is natural and clean.",
        "Looking out of a rainy window in a high-rise apartment. The reflection of the face is visible in the glass, superimposed over the city lights outside. The lighting is very dim, coming only from the phone screen illuminating the face from below. Moody, emotional, and highly realistic.",
        "An ultra-high-resolution medium format extreme close-up portrait of a woman standing near to a indoor wall. Soft, diffused natural daylight from a window illuminates her face and hand evenly, creating a clean, hydrated skin finish that is not oily or greasy. The focus is razor-sharp on the skin of her cheek right next to the bottle and her fingertips holding it. Upon zooming, extreme micro-details are visible: individual pores, natural skin texture variation, fine vellus hair on the cheek and upper lip, tiny freckles, natural imperfections, and the realistic texture of her cuticles and fingernails. She is looking directly at the camera with a genuine, trustworthy, soft smile, eyes crinkling slightly. She is wearing a simple white cotton robe. The background is a very softly blurred, bright, clean bathroom setting with natural light tones. Shot on Phase One IQ4 150MP Camera System (giving 4K+ resolution clarity), Schneider Kreuznach 120mm Macro f/4 Lens, aperture f/8 for deep focus across the skin texture, ISO 100. Keep her face identity exactly consistent from reference photos provided."

    ],
    PROFESSIONAL: [
        // Vibe: LinkedIn, Founder, Environmental, Soft Light, High Trust
        "Vertical professional headshot, medium shot, standing in a modern open-plan office with glass walls. Soft natural light flooding in from the side, creating a clean look. Wearing a sharp navy blazer over a crisp shirt. Confident, approachable smile, looking directly at the camera. Background is a creamy bokeh of office plants and architectural details. Skin texture is high fidelity and natural.",
        "Candid professional portrait sitting on a stool in a creative studio loft with exposed brick walls in the background. Arms crossed loosely, leaning forward slightly with an engaging expression. Lighting is soft and directional (Rembrandt style), highlighting facial structure without harsh shadows. Wearing smart-casual attire. Skin looks authentic with a natural finish.",
        "Vertical environmental headshot standing in a indoor office environment during the day (financial district). The background is extremely blurred (f/1.8 aperture) showing vague city colors but no distractions. Wearing a tailored fitting suit or coat. The lighting is open shade (soft, even light). Expression is serious but approachable. High resolution skin details.",
        "A clean, high-end studio headshot against a charcoal or dark textured backdrop. Lighting is a 'clam-shell' setup giving a clean, professional look that illuminates the face evenly while retaining dimension. Wearing a minimalist black turtleneck or sweater (Steve Jobs vibe). Gaze is intense and confident. Skin texture is pristine but real, not plastic.",
        "Professional lifestyle shot sitting at a wooden table in a high-end coffee shop or co-working space, laptop open in front (blurred in foreground). Looking up from work with a warm, welcoming smile. Natural window light hits the face from the left. Background shows the interior out of focus. Wearing business casual. Authentic skin texture."
    ]
};