export const REFERENCE_PROMPTS = {
    FLASH: [
        // Vibe: Night out, Party, Hard Direct Flash, Chaos
        "Vertical action shot, half body, sitting on a swing in a dark park at night. The camera is close, using a direct flash to freeze her movement mid-swing. Her hair is flying wildly across her face, and she is smiling widely with her head thrown back. The flash creates a pitch-black background. Skin texture is high fidelity and realistic.",
        "Candid half body shot sitting on the concrete curb outside a bright 24-hour convenience store. Holding a bottle of water, looking up at the camera with a tired but content smirk. The lighting is a mix of the bright white fluorescent store light and a front-facing camera flash. Highlighting the natural texture of the skin.",
        "Vertical flash photography, half body shot standing near the edge of a rooftop railing. Looking out at the city view, profile visible. The flash hits from the side, illuminating hair strands individually and creating a sharp shadow on the neck. Skin looks incredibly realistic and unretouched. Background is a bokeh field of city lights.",
        "A grainy, direct flash photograph taken inside a brightly lit, slightly rundown 24-hour diner at 1 AM. Sitting in a red vinyl booth, bursting out laughing, covering mouth with one hand. Harsh flash mixes with overhead fluorescent lights, creating a slightly greenish tint and a natural sheen on the skin.",
        "Vertical, raw snapshot taken from the driver's seat looking at the passenger in a parked car at night. The harsh, yellowish overhead dome light inside the car is turned on, casting strong downward shadows on the face, highlighting bone structure. Smiling broadly, looking down at a phone with natural skin details."
    ],
    GOLDEN: [
        // Vibe: Sun, Warmth, Morning/Sunset, 35mm Film
        "A candid, documentary-style photograph walking through a busy outdoor farmer's market on a sunny Saturday morning. Laughing, turning head to look back. Bright, harsh sunlight hits face directly from the side, revealing natural skin texture and fine details around the eyes. Shot on 35mm film, Portra 400.",
        "Vertical, candid shot sitting at an outdoor cafe patio. It is late afternoon. Leaning forward, elbows on the table, listening intently with a soft smile. Dappled sunlight filters through the trees, creating shifting patterns of light and shadow on the face. Skin texture is natural and highly detailed.",
        "A raw, hyper-realistic photo resting on a park lawn after a bike ride. It is golden hour. Lying on stomach, propped up on elbows, looking up at the camera with a relaxed expression. The low, warm sun highlights individual strands of messy hair and casts a golden glow on skin, preserving authentic facial details.",
        "Vertical shot standing on a beach boardwalk during sunset. The sun is directly behind the subject, creating a beautiful rim light halo around the hair. The face is softly illuminated by the ambient warm glow. Wind is blowing hair slightly. Skin looks warm, natural, and sun-kissed.",
        "Candid car selfie taken from the passenger seat while driving on a highway. The window is down, and the golden hour sun is blasting in, illuminating the face with a warm, orange hue. Sunglasses on head, laughing at the wind. High resolution texture showing true-to-life skin details."
    ],
    GRITTY: [
        // Vibe: Street, Urban, Raw, High ISO, Cold
        "A gritty, candid flash shot sitting side-by-side on a concrete curb late at night, finishing street food. Wiping the corner of mouth with the back of hand, laughing. The direct flash highlights the humidity on skin, making it look dewy and realistic. Background is dark asphalt and blurry lights.",
        "Vertical snapshot taken under a glass bus stop shelter at night. It is cold outside. Head resting on shoulder, eyes half-closed, looking sleepy and content. The direct camera flash reflects slightly off the glass behind and highlights naturally flushed cheeks from the cold air. Skin texture is raw and unretouched.",
        "Vertical, candid shot standing on a crowded city subway train. Looking out the window with a pensive expression, head resting lightly against the glass. Daylight streams in, illuminating dust motes in the air and the texture of skin, showing natural flush and authentic details.",
        "Black and white street photography style. Walking out of a metro station in the rain, holding a newspaper over head. The image is high contrast with grain. The focus is sharp on the eyes, showing raw emotion and natural facial structure without smoothing.",
        "Late night snapshot leaning against a brick wall in an alleyway, holding a lit cigarette (or phone). The lighting is dim and moody, coming from a distant street lamp. The image has high ISO noise/grain. The face is partially in shadow, emphasizing realistic bone structure and skin texture.",
        "Create a raw, documentary-style shot of a me standing by a railing along a city waterfront promenade. It is late afternoon, and the sun is warm. He is looking out over the water, hands in his jacket pockets. A light breeze is blowing his hair slightly. His expression is pensive and calm, with a subtle, almost imperceptible smile. The low sun angle catches the texture of his skin and stubble clearly. The background is the sparkling water and a distant city skyline. Shot on Canon EOS R5, 50mm lens, showing natural grain. Keep his face identity consistent from reference photos provided."
    ],
    CINE: [
        // Vibe: Atmospheric, Neon, No Flash, Moody, Bokeh
        "Vertical candid shot standing on a windy rooftop overlook at night. Leaning against the railing, hair blowing wildly across face, smiling broadly. Illuminated solely by the ambient city glow and a nearby red neon sign, casting a moody hue on the face. Skin texture is detailed and natural against a bokeh skyline.",
        "Cinematic close-up inside a dimly lit jazz bar. Leaning against the velvet booth, holding a glass. The lighting is soft and warm, coming from a table lamp, creating a 'Rembrandt' triangle of light on the cheek. Deep shadows, rich colors. Skin looks authentic and high fidelity.",
        "Vertical shot walking down a rainy street in Tokyo at night. Holding a clear umbrella. The face is illuminated by the glow of blue and pink shop signs reflecting off the wet pavement. No flash. The look is moody and atmospheric with soft focus background.",
        "A quiet moment inside a late-night laundromat. Sitting on top of a washing machine, reading a book. The lighting is cool, clinical white from the fluorescent tubes, but soft and diffused. The composition is symmetrical (Wes Anderson style). Skin texture is natural and clean.",
        "Looking out of a rainy window in a high-rise apartment. The reflection of the face is visible in the glass, superimposed over the city lights outside. The lighting is very dim, coming only from the phone screen illuminating the face from below. Moody, emotional, and highly realistic.",
        "An ultra-high-resolution medium format extreme close-up portrait of a woman standing near to a indoor wall. Soft, diffused natural daylight from a window illuminates her face and hand evenly, creating a clean, hydrated skin finish that is not oily or greasy. The focus is razor-sharp on the skin of her cheek right next to the bottle and her fingertips holding it. Upon zooming, extreme micro-details are visible: individual pores, natural skin texture variation, fine vellus hair on the cheek and upper lip, tiny freckles, natural imperfections, and the realistic texture of her cuticles and fingernails. She is looking directly at the camera with a genuine, trustworthy, soft smile, eyes crinkling slightly. She is wearing a simple white cotton robe. The background is a very softly blurred, bright, clean bathroom setting with natural light tones. Shot on Phase One IQ4 150MP Camera System (giving 4K+ resolution clarity), Schneider Kreuznach 120mm Macro f/4 Lens, aperture f/8 for deep focus across the skin texture, ISO 100. Keep her face identity exactly consistent from reference photos provided."

    ],
    PROFESSIONAL: [
        // Vibe: LinkedIn, Founder, Environmental, Soft Light, High Trust
        "Vertical professional headshot, medium shot, standing in a modern open-plan office with glass walls. Soft natural light flooding in from the side, creating a clean look. Wearing a sharp navy blazer over a crisp shirt. Confident, approachable smile, looking directly at the camera. Background is a creamy bokeh of office plants and architectural details. Skin texture is high fidelity and natural.",
        "Candid professional portrait sitting on a stool in a creative studio loft with exposed brick walls in the background. Arms crossed loosely, leaning forward slightly with an engaging expression. Lighting is soft and directional (Rembrandt style), highlighting facial structure without harsh shadows. Wearing smart-casual attire. Skin looks authentic with a natural finish.",
        "Vertical environmental headshot standing in a indoor office environment during the day (financial district). The background is extremely blurred (f/1.8 aperture) showing vague city colors but no distractions. Wearing a tailored fitting suit or coat. The lighting is open shade (soft, even light). Expression is serious but approachable. High resolution skin details.",
        "A clean, high-end studio headshot against a charcoal or dark textured backdrop. Lighting is a 'clam-shell' setup giving a clean, professional look that illuminates the face evenly while retaining dimension. Wearing a minimalist black turtleneck or sweater (Steve Jobs vibe). Gaze is intense and confident. Skin texture is pristine but real, not plastic.",
        "Professional lifestyle shot sitting at a wooden table in a high-end coffee shop or co-working space, laptop open in front (blurred in foreground). Looking up from work with a warm, welcoming smile. Natural window light hits the face from the left. Background shows the interior out of focus. Wearing business casual. Authentic skin texture."
    ]
};