-- Migration: Refactor follow-up emails to support multiple stages
-- Step 1: Drop the old table (if logic allows, or we can just ignore it)
drop table if exists public.one_day_followup_emails;

-- Step 2: Create universal tracking table
create table public.followup_email_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email_type text not null, -- '30min' or '4hour'
  sent_at timestamp with time zone default now(),
  unique(user_id, email_type) -- Ensure we don't send the same type twice
);

-- Enable Row Level Security (RLS)
alter table public.followup_email_logs enable row level security;

-- Create policy to DENY all access by default (Authenticated and Anon users)
-- Only the Service Role (used by the API) can bypass this.
create policy "Service role only"
  on public.followup_email_logs
  for all
  using ( false ); -- Explicitly deny everyone else

-- Step 3: Create flexible function to finding users
-- Parameters:
--   start_offset: e.g. '30 minutes'
--   end_offset:   e.g. '1 hour 30 minutes' (Buffer window)
--   target_type:  e.g. '30min'
create or replace function public.get_eligible_users_for_followup(
  start_offset interval,
  end_offset interval,
  target_email_type text
)
returns table (
  id uuid,
  email varchar
) 
language sql
security definer
as $$
  select 
    au.id,
    au.email::varchar
  from auth.users au
  where 
    -- 1. User created within the target window
    au.created_at < (now() - start_offset)
    and au.created_at > (now() - end_offset)
    
    -- 2. Has NOT received THIS specific email type
    and not exists (
      select 1 
      from public.followup_email_logs fel
      where fel.user_id = au.id
      and fel.email_type = target_email_type
    )
    
    -- 3. Has NO credits
    and not exists (
      select 1 
      from public.credits c 
      where c.user_id = au.id
    )
    
    -- 4. Has NO successful payments
    and not exists (
      select 1 
      from public.dodo_payments dp 
      where dp.user_id = au.id 
      and dp.status = 'completed'
    )
$$;
